---
- name: zabbix-server restarted
  systemd:
    name: zabbix-server
    state: restarted
    enabled: yes

- name: restart apache
  systemd:
    name: apache2
    state: restarted
    enabled: yes

...
